version: "3.8"

services:
  mydb:
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    networks:
      - dockercompose-frontend
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 15s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mydb
      PMA_PORT: 3306
    depends_on:
      mydb:
        condition: service_healthy
    ports:
      - "8080:80"
    networks:
      - dockercompose-frontend

networks:
  dockercompose-frontend:

volumes:
  mysql-data:
