version: "3.8"

networks:
  dockercompose-frontend:

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - dockercompose-frontend
    depends_on:
      - mydb
    environment:
      PMA_HOST: mydb
      PMA_PORT: 3306

  mydb:
    build: ./mydb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - dockercompose-frontend
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
